# -*- coding: utf-8 -*-
"""boston.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jOK8zTqjzKpooK-D9HBw0jeEn8Aoy9tK
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("BostonHousing.csv")
print(df.head())

X = df.drop("medv",axis =1)
Y = df["medv"]

X_train , X_test ,Y_train , Y_test = train_test_split(X,Y,test_size =0.2 , random_state =42)

Scaler=StandardScaler()

X_train = Scaler.fit_transform(X_train)
X_test = Scaler.transform(X_test)

model = Sequential()
model.add(Dense(64, activation='relu',input_shape =(X_train.shape[1],)))
model.add(Dense(32,activation='relu'))
model.add(Dense(1))

model.compile(
    optimizer = 'adam',
    loss ='mse',
    metrics=['mae'])

history =model.fit(X_train ,Y_train,epochs = 100 , batch_size=16,validation_split =0.1 , verbose=1)

loss , mae = model.evaluate(X_test , Y_test)
print("Test loss (Mse) : " ,loss)
print("Test MAE : " , mae)

y_pred = model.predict(X_test)

for i in range(5):
  print(f"Actual : {Y_test.iloc[i]} Predicted : {y_pred[i][0]}")

plt.scatter(Y_test,y_pred)
plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")
plt.title("Actual VS Predicted Prices")
plt.show()