# -*- coding: utf-8 -*-
"""fashsion_msnist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UOO-9MXTSR72ZltHDkxxWjdmHmYRdHOe
"""

import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.fashion_mnist.load_data()

train_images = train_images / 255.0
test_images = test_images / 255.0

train_images = train_images.reshape(-1, 28, 28, 1)
test_images = test_images.reshape(-1, 28, 28, 1)

model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(10, activation='softmax')
])

# Compile
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(train_images, train_labels, epochs=5)

loss, acc = model.evaluate(test_images, test_labels)
print("Accuracy:", acc)

class_names = ['T-shirt', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

plt.imshow(test_images[0].reshape(28,28), cmap='gray')
plt.title(class_names[test_labels[0]])
plt.show()

predictions = model.predict(test_images)

plt.figure(figsize=(10,10))

for i in range(16):
    plt.subplot(4,4,i+1)
    plt.imshow(test_images[i].reshape(28,28), cmap='gray')

    predicted_label = class_names[predictions[i].argmax()]
    actual_label = class_names[test_labels[i]]

    plt.title(f"P: {predicted_label}\nA: {actual_label}")
    plt.axis('off')

plt.show()