# -*- coding: utf-8 -*-
"""IMDB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/167BxSSqDuNXI0zuFTGLmnoFDATdj5WxC
"""

import numpy as np
import matplotlib.pyplot as plt

from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Keep only top 10,000 most frequent words
vocab_size = 10000

(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=vocab_size)

print("Training samples:", len(X_train))
print("Test samples:", len(X_test))

max_len=200
X_train = pad_sequences(X_train , maxlen=max_len)
X_test = pad_sequences(X_test, maxlen = max_len)

model = Sequential()
model.add(Dense(128, activation ='relu', input_shape=(max_len,)))
model.add(Dense(64,activation ='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(
    optimizer ='adam',
    loss ='binary_crossentropy',
    metrics=['accuracy']
)

history=model.fit(X_train ,y_train , epochs = 10 , batch_size=32,validation_split=0.2)

loss,acc=model.evaluate(X_test, y_test)
print("Accuracy :", acc)

pred = model.predict(X_test)

y_pred = (pred>0.5).astype(int)

for i in range(5):
  print("Actual :" , y_test[i] , "Predicted : " , y_pred[i][0] )

plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')

plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.title("Model Accuracy")
plt.legend()
plt.show()