# -*- coding: utf-8 -*-
"""imdb(dataset).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nDnzbXSS_cwodD9Rg6OtTZNaULXosNVV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("IMDB Dataset.csv")
print(df.head())



df['sentiment']=df['sentiment'].map({
    'positive' : 1 ,
    'negative' :0
    })

X=df['review'].values
Y= df['sentiment'].values

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

vocab_size = 10000

tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(X_train)

X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

max_len = 200

X_train_pad = pad_sequences(X_train_seq, maxlen=max_len)
X_test_pad = pad_sequences(X_test_seq, maxlen=max_len)

model = Sequential()
model.add(Dense(128, activation ='relu', input_shape=(max_len,)))
model.add(Dense(64,activation ='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(
    optimizer ='adam',
    loss ='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train_pad, y_train,
    epochs=10,
    batch_size=32,
    validation_split=0.2
)

loss, acc = model.evaluate(X_test_pad, y_test)
print("Accuracy:", acc)

plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')

plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.title("Model Accuracy")
plt.legend()
plt.show()