# -*- coding: utf-8 -*-
"""Letter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lJHNS1vBD41r6oZEwRnSlfQ7OGHvnIbE
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

from google.colab import files
uploaded = files.upload()

columns = ["letter"] + [f"feature_{i}" for i in range(1, 17)]
df = pd.read_csv("letter-recognition.csv", header=None, names=columns, skiprows=1)

print(df.head())

X=df.iloc[:, 1:].values
Y= df.iloc[: ,0].values

encoder = LabelEncoder()

y_encoded = encoder.fit_transform(Y)
y_categorical = to_categorical(y_encoded)

X_train ,X_test ,Y_train , Y_test = train_test_split(X,y_categorical , test_size=0.2 , random_state= 42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = Sequential()

model.add(Dense(128 ,activation='relu', input_shape = (16,)))
model.add(Dense(64 , activation='relu'))
model.add(Dense(26,activation ='softmax'))

model.compile(
    optimizer = 'adam',
    loss="categorical_crossentropy",
    metrics=['accuracy']
)

history = model.fit(X_train , Y_train , epochs = 30 , batch_size = 32 , validation_split=0.1)

loss, acc = model.evaluate(X_test, Y_test)
print("Accuracy : ", acc)

y_pred = model.predict(X_test)
y_pred_label = np.argmax(y_pred, axis=1)
y_true_label= np.argmax(Y_test, axis =1)

predicted_letters = encoder.inverse_transform(y_pred_label)
actual_letters = encoder.inverse_transform(y_true_label)

for i in range(5):
  print(f"Actual Letters {actual_letters[i]}, Predicted Letters : {predicted_letters[i]}")

plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')

plt.title("Model Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend()
plt.show()