# -*- coding: utf-8 -*-
"""Plant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ai9lEbchMm-4vHOcXtadgvjNODBlQbUW
"""

!pip install tensorflow matplotlib numpy opencv-python

import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import numpy as np
from tensorflow.keras.preprocessing import image

from google.colab import files
files.upload()

import zipfile

zip_ref = zipfile.ZipFile("PlantVillage-Dataset.zip", 'r')
zip_ref.extractall("/content/dataset")
zip_ref.close()
data_dir = "/content/dataset"

import os
print(os.listdir("/content/dataset"))

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="training",
    seed=123,
    image_size=(128,128),
    batch_size=32
)

val_ds = tf.keras.preprocessing.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=(128,128),
    batch_size=32
)

class_names = train_ds.class_names
print("Classes:", class_names)

AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.prefetch(buffer_size=AUTOTUNE)

model = models.Sequential([
    layers.Rescaling(1./255, input_shape=(128,128,3)),

    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),

    layers.Conv2D(32,3,activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(64,3,activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(128,3,activation='relu'),
    layers.MaxPooling2D(),

    layers.Flatten(),

    layers.Dense(128,activation='relu'),
    layers.Dense(len(class_names),activation='softmax')
])
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10
)

plt.plot(history.history['accuracy'], label='Train')
plt.plot(history.history['val_accuracy'], label='Validation')
plt.legend()
plt.title("Accuracy")
plt.show()

model.save("plant_model.keras")
print("Model Saved")

plt.figure(figsize=(10,10))

for images, labels in val_ds.take(1):
    predictions = model.predict(images)
    pred_labels = np.argmax(predictions, axis=1)

    for i in range(12):
        plt.subplot(4,3,i+1)
        plt.imshow(images[i].numpy().astype("uint8"))

        actual = class_names[labels[i]]
        predicted = class_names[pred_labels[i]]

        plt.title(f"A: {actual}\nP: {predicted}")
        plt.axis("off")

plt.tight_layout()
plt.show()

loss, acc = model.evaluate(val_ds)
print("Accuracy:", acc)