# -*- coding: utf-8 -*-
"""RNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m4vmMDHB1WoVWzcjQSzTzD3hLd_y_3W8
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import MinMaxScaler

from google.colab import files
files.upload()

df = pd.read_csv("Google Dataset.csv")
print(df.head())

dataset=df[['Open']].values
print("Dataset Shape", dataset.shape)

split = int(len(dataset)*0.8)
train = dataset[:split]
test = dataset[split:]
print("Train Shape", train.shape)
print("Test Shape", test.shape)

scaler = MinMaxScaler()
train_scaled = scaler.fit_transform(train)

X_train=[]
y_train=[]
time_step=10
for i in range(time_step,len(train_scaled)):
  X_train.append(train_scaled[i-time_step : i])
  y_train.append(train_scaled[i,0])

X_train= np.array(X_train)
y_train = np.array(y_train)
X_train=X_train.reshape(X_train.shape[0],X_train.shape[1],1)
print("X_train Shape", X_train.shape)

model = Sequential()
model.add(LSTM(50,return_sequences=True,input_shape=(X_train.shape[1],1)))
model.add(LSTM(50,return_sequences=True))
model.add(LSTM(50))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

model.fit(X_train, y_train, epochs=5, batch_size=16)

full_data = np.concatenate((train, test), axis=0)
inputs = full_data[len(full_data)-len(test)-time_step:]
inputs = scaler.transform(inputs)

X_test=[]
for i in range(time_step , time_step+len(test)):
  X_test.append(inputs[i-time_step:i])
X_test = np.array(X_test)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

pred_scaled = model.predict(X_test)
predicted = scaler.inverse_transform(pred_scaled)

real = test
rmse = np.sqrt(mean_squared_error(real, predicted))
print("RMSE:", rmse)

# Show results
result = pd.DataFrame({
    "Actual": real.flatten(),
    "Predicted": predicted.flatten()
})

print(result.head(10))

plt.plot(real, label="Actual")
plt.plot(predicted, label="Predicted")
plt.legend()
plt.title("Stock Price Prediction (LSTM)")
plt.show()